server:
  port: 8088 


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: default-zone
    service-url:
      default-zone: http://192.168.1.66:8761/eureka/
  instance:
    hostname: 192.168.1.66

spring:
  application:
    name: API-GATEWAY
  cloud:
   gateway:
     routes:
        - id: PLAYERSERVICE-SERVICE
          uri: http://192.168.1.66:8083/
          predicates:
            - Path=/playerService/**
        - id: TEAM-SERVICE
          uri: http://192.168.1.66:8084/
          predicates:
            - Path=/team/**
        - id: CARDS-SERVICE
          uri: http://192.168.1.66:8085/
          predicates:
              - Path=/cards/**
